apiVersion: apps/v1
kind: Deployment
metadata:
  name: 4-nodes-frontend 
  namespace: twin-sim
  labels:
    app: 4-nodes-frontend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 4-nodes-frontend 
  template:
    metadata:
      labels:
        app: 4-nodes-frontend 
    spec:
      containers:
      - name: 4-nodes-frontend 
        image: emindsguardians/dt-frontend-k8s:twinarcjan2025 # dynamic env
        command: [ "npm", "start"]
        ports:
        - containerPort: 3000

#       env:
#       - name: PORT
#         value: "3000"
#       - name: REACT_APP_BASE_URL
#         value: "https://gateway.dev.twinarc.eminds.ai"
#       - name: REACT_APP_MIDDLEWARE_URL
#         value: "https://api.dev.twinarc.eminds.ai/digital_twin"

      nodeSelector:
        node-type: twinarcworker1
---
apiVersion: v1
kind: Service
metadata:
  name: 4-nodes-frontend 
  namespace: twin-sim
spec:
  type: NodePort
  selector:
    app: 4-nodes-frontend 
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30101