apiVersion: apps/v1
kind: Deployment
metadata:
  name: causal-app-frontend
  namespace: twin-sim
  labels:
    app: causal-app-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: causal-app-frontend
  template:
    metadata:
      labels:
        app: causal-app-frontend
    spec:
      containers:
      - name: causal-app-frontend
        image: emindsguardians/dt-frontend-k8s:twinarcjan2025 # dynamic env
        command: [ "npm", "start"]
        ports:
        - containerPort: 3000

#        env:
#        - name: PORT
#          value: "3000"
#        - name: REACT_APP_BASE_URL
#          value: "https://gateway.dev.twinarc.eminds.ai"
#        - name: REACT_APP_MIDDLEWARE_URL
#          value: "https://api.dev.twinarc.eminds.ai/digital_twin"

      nodeSelector:
        node-type: twinarcworker1
---
apiVersion: v1
kind: Service
metadata:
  name: causal-app-frontend
  namespace: twin-sim
spec:
  type: NodePort
  selector:
    app: causal-app-frontend
  ports:
    - protocol: TCP
      port: 3000
      nodePort: 30105